# Generated by Django 5.1.2 on 2025-11-07 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificacion'),
        ('ot', '0004_ordentrabajo_prioridad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('todo_el_dia', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL)),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='ot.ordentrabajo')),
            ],
            options={
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['inicio'], name='core_evento_inicio_f7f8cb_idx'), models.Index(fields=['asignado_a', 'inicio'], name='core_evento_asignad_fdc8ed_idx')],
            },
        ),
    ]
