# Generated by Django 5.1.2 on 2025-11-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventoagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
