# Generated by Django 5.1.2 on 2025-11-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eventoagenda_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GUARDIA', 'Guardia de Acceso'), ('SUPERVISOR', 'Supervisor de Flota'), ('JEFE_TALLER', 'Jefe del Taller'), ('MECANICO', 'Mecánico'), ('ASISTENTE_REPUESTO', 'Asistente de Repuesto'), ('RECEPCIONISTA', 'Recepcionista de Vehículo')], default='RECEPCIONISTA', max_length=32),
        ),
    ]
