# Generated by Django 5.1.2 on 2025-11-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_config_sessionlog_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='sla_horas',
            field=models.PositiveIntegerField(default=72, help_text='Horas de SLA para cierre de OT'),
        ),
    ]
