# Generated by Django 5.1.2 on 2025-11-01 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('estado_actual', models.CharField(choices=[('ING', 'Ingresado'), ('DIA', 'Diagnóstico'), ('REP', 'Reparación'), ('LIS', 'Listo'), ('ENT', 'Entregado'), ('CER', 'Cerrado')], default='ING', max_length=3)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taller.taller')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taller.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ING', 'Ingresado'), ('DIA', 'Diagnóstico'), ('REP', 'Reparación'), ('LIS', 'Listo'), ('ENT', 'Entregado'), ('CER', 'Cerrado')], max_length=3)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ot.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
            },
        ),
        migrations.CreateModel(
            name='DocumentoOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='docs/')),
                ('tipo', models.CharField(blank=True, max_length=30)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ot.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='PausaOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas', to='ot.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Pausa',
                'verbose_name_plural': 'Pausas',
            },
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['folio'], name='ot_ordentra_folio_9fc3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado_actual'], name='ot_ordentra_estado__de357f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('vehiculo',), name='uq_ot_activa_por_vehiculo'),
        ),
        migrations.AddIndex(
            model_name='historialestadoot',
            index=models.Index(fields=['ot', 'estado', 'inicio'], name='ot_historia_ot_id_3a73f5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoot',
            index=models.Index(fields=['ot', 'ts'], name='ot_document_ot_id_8e983c_idx'),
        ),
        migrations.AddIndex(
            model_name='pausaot',
            index=models.Index(fields=['ot', 'inicio'], name='ot_pausaot_ot_id_fe1ac0_idx'),
        ),
    ]
