# Generated by Django 5.1.2 on 2025-11-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pausaot',
            constraint=models.UniqueConstraint(condition=models.Q(('fin__isnull', True)), fields=('ot',), name='uq_pausa_abierta_por_ot'),
        ),
    ]
