# Generated by Django 5.1.2 on 2025-11-02 02:32

import ot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0002_pausaot_uq_pausa_abierta_por_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoot',
            name='archivo',
            field=models.FileField(upload_to=ot.models.documento_upload_path),
        ),
    ]
