# Generated by Django 5.1.2 on 2025-11-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0003_alter_documentoot_archivo'),
        ('taller', '0002_vehiculo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Crítica')], default=2),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['prioridad'], name='ot_ordentra_priorid_9a2f01_idx'),
        ),
    ]
