# Generated by Django 5.1.2 on 2025-11-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0005_ordentrabajo_fecha_compromiso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='chofer',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
