# Generated by Django 5.1.2 on 2025-11-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0006_ordentrabajo_chofer'),
        ('taller', '0003_tipovehiculo_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ots', to='taller.vehiculo'),
        ),
    ]
