# Generated by Django 5.1.2 on 2025-11-08 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0007_alter_ordentrabajo_vehiculo'),
        ('taller', '0003_tipovehiculo_vehiculo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ordentrabajo',
            name='uq_ot_activa_por_vehiculo',
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('vehiculo',), name='uniq_ot_activa_por_vehiculo'),
        ),
    ]
