# Generated by Django 5.1.2 on 2025-11-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0008_remove_ordentrabajo_uq_ot_activa_por_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestadoot',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
