# Generated by Django 5.1.2 on 2025-11-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('TALLER', 'En taller'), ('FUERA', 'Fuera de servicio'), ('OPER', 'Operativo')], default='OPER', max_length=10),
        ),
    ]
